spring:
  kafka:
    topic: 'library-events'
    admin:
      properties:
        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
